
const getters = {
  tag: state => state.tags.tag,
  isCollapse: state => state.common.isCollapse,
  isLock: state => state.common.isLock,
  isFullScren: state => state.common.isFullScren,
  isIndex: state => state.common.isIndex,
  showPanel: state => state.common.showPanel,
  searchBox: state => state.common.searchBox,
  isRouterAlive: state => state.common.isRouterAlive,
  lockPasswd: state => state.common.lockPasswd,
  tagList: state => state.tags.tagList,
  tagCurrent: state => state.tags.tagCurrent,
  tagWel: state => state.tags.tagWel,
  accessToken: state => state.user.accessToken,
  refreshToken: state => state.user.refreshToken,
  userInfo: state => state.user.userInfo,
  userInfoPass:state=>state.user.userInfoPass,
  loadingStatus: state => state.common.loadingStatus,
  clientWidth: state => state.screen.clientWidth,
  clientHeight: state => state.screen.clientHeight,
  tableSize: state => state.screen.tableSize,
  workspaceRect: state => state.screen.workspaceRect,
  dicts: state => state.common.dicts,
  menuRouters: state => state.user.menuRouters,
  menu: state => state.user.menu,
  isShowEmployee:state=>state.common.isShowEmployee,
  requestCount:state=>state.common.requestCount,
  axiosLoading:state=>state.common.axiosLoading,
  requestEndTimer:state=>state.common.requestEndTimer,
  prevRequsetEndTime:state=>state.common.prevRequsetEndTime,
};
export default getters;
